/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/ws/{deviceId}/resume_queued': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: {
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/navigation/{deviceId}/update_mapbox_token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: {
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateMapboxTokenRequestModel'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/navigation/{deviceId}/set_destination': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: {
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['SetNavigationDestinationRequestModel'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/navigation/{deviceId}/locations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['SavedLocationResponseModel'][];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/settings/{deviceId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Gets all the available settings on the device.
		 * @deprecated
		 * @description That means all the params available to save and request, but no data is returned with this.
		 */
		get: {
			parameters: {
				query?: {
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AvailableSettingsResponseModel'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Pushes settings to the device.
		 * @description Settings are pushed real-time through a secure websocket connection.<br /><b>For sponsors</b>: If device is offline, messages are placed on an internal queue until the device is connected to push the messages.
		 */
		post: {
			parameters: {
				query?: {
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['ParamRequestModel'][];
				};
			};
			responses: {
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/settings/{deviceId}/values': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Gets all the current settings on the device.
		 * @deprecated
		 * @description These settings are not stored on server, they are just obtained real-time from the device through a secure websocket connection.
		 */
		get: {
			parameters: {
				query: {
					paramKeys: string[];
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['CurrentSettingsResponseModel'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/settings/{deviceId}/{paramKey}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Gets a specific settings from the device.
		 * @deprecated
		 */
		get: {
			parameters: {
				query?: {
					/** @description The requested API version */
					'api-version'?: string;
				};
				header?: never;
				path: {
					deviceId: string;
					paramKey: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['CurrentSettingsResponseModel'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/backup/{deviceId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Latest Device Backup
		 * @deprecated
		 * @description Retrieves the latest backup configuration for a specific device.
		 */
		get: operations['GetDeviceBackup'];
		/**
		 * Update Device Backup
		 * @description Creates or updates a backup configuration for a device. If the backup does not exist, it's created; otherwise, it's updated.
		 */
		put: operations['UpdateDeviceBackup'];
		post?: never;
		/**
		 * Delete Device Backups
		 * @description Deletes all backup configurations for a specific device.
		 */
		delete: operations['DeleteDeviceBackup'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/backup/{deviceId}/{backupVersion}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Specific Version Device Backup
		 * @deprecated
		 * @description Retrieves the requested version backup configuration for a specific device.
		 */
		get: operations['GetDeviceBackupVersion'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/backup/{deviceId}/history': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Device Backup History
		 * @deprecated
		 * @description Retrieves all backup versions for a specific device.
		 */
		get: operations['GetAllDeviceBackups'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApiTokenModel: {
			token?: string | null;
			device_id?: string | null;
			/** Format: date-time */
			expiration_date?: string;
			readonly is_expired?: boolean;
			readonly is_active?: boolean;
			is_deactivated?: boolean;
		};
		AvailableSettingsResponseModel: {
			keys?: string[] | null;
		};
		BackupMetadataModel: {
			key: string | null;
			value: string | null;
			tags?: string[] | null;
		};
		BackupRequestModel: {
			is_encrypted?: boolean;
			config: string | null;
			sunnypilot_version: components['schemas']['SunnypilotVersion'];
			backup_metadata?: components['schemas']['BackupMetadataModel'][] | null;
		};
		BackupResponseModel: {
			device_id: string | null;
			/** Format: int32 */
			version?: number;
			is_encrypted?: boolean;
			config: string | null;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
			sunnypilot_version: components['schemas']['SunnypilotVersion'];
			backup_metadata?: components['schemas']['BackupMetadataModel'][] | null;
		};
		CurrentSettingsResponseModel: {
			readonly settings?: {
				[key: string]: string;
			} | null;
			_settings_v1?: components['schemas']['DeviceParam'][] | null;
		};
		DeviceAuthPatchRequestModel: {
			alias?: string | null;
		};
		DeviceAuthRegistrationResponseModel: {
			readonly dongle_id?: string | null;
			device_id?: string | null;
		};
		DeviceAuthResponseModel: {
			device_id: string | null;
			/** Format: int32 */
			version?: number;
			comma_dongle_id?: string | null;
			alias?: string | null;
			public_key: string | null;
			/** Format: int64 */
			created_at?: number;
			/** Format: int64 */
			updated_at?: number;
		};
		DeviceParam: {
			key?: string | null;
			is_compressed?: boolean;
			value?: string | null;
			/** @enum {string} */
			type?: 'String' | 'Bool' | 'Int' | 'Float' | 'Time' | 'Json' | 'Bytes' | 'Unknown';
		};
		DeviceUserResponseModel: {
			device_id?: string | null;
			user_id?: string | null;
			/** Format: int64 */
			created_at?: number;
			/** Format: int64 */
			updated_at?: number;
			/** Format: byte */
			token_hash?: string | null;
		};
		GoogleTokenModel: {
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
			/** Format: int32 */
			version?: number;
			/** Format: int32 */
			last_version?: number | null;
			access_token?: string | null;
			/** Format: int32 */
			expires_in?: number;
			/** Format: date-time */
			readonly valid_until?: string;
			scope?: string | null;
			token_type?: string | null;
			refresh_token?: string | null;
			device_id?: string | null;
		};
		IRoleResponseModel: {
			/** @enum {string} */
			role_type?: 'ReadOnly' | 'Sponsor' | 'Admin' | 'Discourse';
		};
		NoContent: {
			/** Format: int32 */
			readonly status_code?: number;
		};
		ParamRequestModel: {
			key?: string | null;
			value?: string | null;
			is_compressed?: boolean;
		};
		PostSponsorRequestModel: {
			user_id: string | null;
			/** @enum {string} */
			sponsor_tier?: 'Free' | 'Novice' | 'Supporter' | 'Contributor' | 'Benefactor' | 'Guardian';
			/** Format: int32 */
			duration_hours?: number;
		};
		ProblemDetails: {
			type?: string | null;
			title?: string | null;
			/** Format: int32 */
			status?: number | null;
			detail?: string | null;
			instance?: string | null;
		} & {
			[key: string]: unknown;
		};
		RoleResponseModel2: {
			/** @enum {string} */
			role_type?: 'ReadOnly' | 'Sponsor' | 'Admin' | 'Discourse';
			role_tier?: string | null;
		};
		RouteFile: {
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
			/** Format: int32 */
			version?: number;
			/** Format: int32 */
			last_version?: number | null;
			name?: string | null;
			path?: string | null;
			route_id?: string | null;
			device_id?: string | null;
			/** Format: int32 */
			segment_id?: number | null;
			download_uri?: string | null;
		};
		RouteModel: {
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
			/** Format: int32 */
			version?: number;
			/** Format: int32 */
			last_version?: number | null;
			alias?: string | null;
			device_id?: string | null;
			is_public?: boolean;
			/** Format: int32 */
			segment_count?: number;
			route_id?: string | null;
			segments?: components['schemas']['RouteSegment'][] | null;
		};
		RouteSegment: {
			device_id?: string | null;
			route_id?: string | null;
			/** Format: int32 */
			segment_id?: number;
			files?: components['schemas']['RouteFile'][] | null;
		};
		SavedLocationResponseModel: {
			/** Format: int32 */
			id?: number;
			dongle_id: string | null;
			place_name?: string | null;
			place_details?: string | null;
			/** Format: double */
			latitude?: number;
			/** Format: double */
			longitude?: number;
			/** @enum {string} */
			save_type?: 'Recent' | 'Favorite';
			label?: string | null;
			/** Format: date-time */
			modified?: string;
		};
		SetNavigationDestinationRequestModel: {
			/** Format: double */
			latitude?: number;
			/** Format: double */
			longitude?: number;
			place_name?: string | null;
			place_details?: string | null;
		};
		SunnypilotVersion: {
			/** Format: int32 */
			major?: number;
			/** Format: int32 */
			minor?: number;
			/** Format: int32 */
			patch?: number;
			/** Format: int32 */
			build?: number;
			branch?: string | null;
		};
		UpdateMapboxTokenRequestModel: {
			public_token?: string | null;
			app_token?: string | null;
		};
		UploadFileToUrlResponse: {
			/** Format: int32 */
			enqueued?: number;
			items?: components['schemas']['UploadItem'][] | null;
			failed?: string[] | null;
		};
		UploadItem: {
			path?: string | null;
			url?: string | null;
			headers?: {
				[key: string]: string;
			} | null;
			/** Format: int64 */
			created_at?: number;
			id?: string | null;
			/** Format: int32 */
			retry_count?: number;
			current?: boolean;
			/** Format: float */
			progress?: number;
			allow_cellular?: boolean;
		};
		UploadUrlModel: {
			file_name?: string | null;
			url?: string | null;
			headers?: {
				[key: string]: string;
			} | null;
		};
		UserRequestModel: {
			user_id?: string | null;
		};
		UserResponseModel: {
			user_id?: string | null;
			roles?: components['schemas']['IRoleResponseModel'][] | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	GetDeviceBackup: {
		parameters: {
			query?: {
				/** @description The requested API version */
				'api-version'?: string;
			};
			header?: never;
			path: {
				deviceId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BackupResponseModel'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ProblemDetails'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ProblemDetails'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ProblemDetails'];
				};
			};
		};
	};
	UpdateDeviceBackup: {
		parameters: {
			query?: {
				/** @description The requested API version */
				'api-version'?: string;
			};
			header?: never;
			path: {
				deviceId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BackupRequestModel'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BackupResponseModel'];
				};
			};
		};
	};
	DeleteDeviceBackup: {
		parameters: {
			query?: {
				/** @description The requested API version */
				'api-version'?: string;
			};
			header?: never;
			path: {
				deviceId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GetDeviceBackupVersion: {
		parameters: {
			query?: {
				/** @description The requested API version */
				'api-version'?: string;
			};
			header?: never;
			path: {
				deviceId: string;
				backupVersion: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BackupResponseModel'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ProblemDetails'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ProblemDetails'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ProblemDetails'];
				};
			};
		};
	};
	GetAllDeviceBackups: {
		parameters: {
			query?: {
				/** @description The requested API version */
				'api-version'?: string;
			};
			header?: never;
			path: {
				deviceId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BackupResponseModel'][];
				};
			};
		};
	};
}
