export type SettingCategory = 'device' | 'toggles' | 'steering' | 'cruise' | 'visuals' | 'developer' | 'other';

export interface SettingDefinition {
    key: string;
    label: string;
    description: string;
    category: SettingCategory;
    advanced?: boolean;
    readonly?: boolean;
    hidden?: boolean;
}

export const SETTINGS_DEFINITIONS: SettingDefinition[] = [
    // Device
    { key: 'DongleId', label: 'Dongle ID', description: 'Unique device identifier', category: 'device', readonly: true },
    { key: 'GitCommit', label: 'Git Commit', description: 'Current software version', category: 'device' },
    { key: 'GithubSshKeys', label: 'GitHub SSH Keys', description: 'SSH keys for GitHub access', category: 'device' },
    { key: 'GithubUsername', label: 'GitHub Username', description: 'Connected GitHub account', category: 'device' },
    { key: 'GsmMetered', label: 'GSM Metered', description: 'Cellular data metering', category: 'device' },
    { key: 'IsLdwEnabled', label: 'LDW Enabled', description: 'Lane departure warnings', category: 'device' },
    { key: 'IsMetric', label: 'Metric Units', description: 'Display metric measurements', category: 'device' },
    { key: 'LanguageSetting', label: 'Language', description: 'UI language', category: 'device' },
    { key: 'OpenpilotEnabledToggle', label: 'Openpilot Enabled', description: 'Master openpilot toggle', category: 'device' },
    { key: 'RecordFront', label: 'Record Front', description: 'Front camera recording', category: 'device' },
    { key: 'IsRHD', label: 'Right-Hand Drive', description: 'RHD vehicle configuration', category: 'device' },
    { key: 'Version', label: 'Version', description: 'Software version number', category: 'device', readonly: true },
    { key: 'QuietMode', label: 'QuietMode', description: 'Unknown setting from device', category: 'device' },
    { key: 'MaxTimeOffroad', label: 'MaxTimeOffroad', description: 'Unknown setting from device', category: 'device', advanced: true },

    // Toggles
    { key: 'DisableLogging', label: 'Disable Logging', description: 'Stop data logging', category: 'toggles', advanced: true },
    { key: 'DisableOnroadUploads', label: 'Disable Onroad Uploads', description: 'No uploads while driving', category: 'toggles' },
    { key: 'DisablePowerDown', label: 'Disable Power Down', description: 'Stay on after ignition off', category: 'toggles', advanced: true },
    { key: 'DisableUpdates', label: 'Disable Updates', description: 'Skip software updates', category: 'toggles', advanced: true },
    { key: 'EnableWideCamera', label: 'Wide Camera', description: 'Use wide-angle camera', category: 'toggles', advanced: true },

    // Steering
    { key: 'EndToEndLong', label: 'End-to-End Long', description: 'E2E longitudinal control', category: 'steering' },
    { key: 'LongitudinalPersonality', label: 'Personality', description: 'Driving style preference', category: 'steering' },
    { key: 'LiveTorqueParamsToggle', label: 'LiveTorqueParamsToggle', description: 'Unknown setting from device', category: 'steering' },
    { key: 'EnforceTorqueControl', label: 'EnforceTorqueControl', description: 'Unknown setting from device', category: 'steering' },
    { key: 'NeuralNetworkLateralControl', label: 'NeuralNetworkLateralControl', description: 'Unknown setting from device', category: 'steering' },
    { key: 'MadsSteeringMode', label: 'MadsSteeringMode', description: 'Unknown setting from device', category: 'steering' },
    { key: 'MadsMainCruiseAllowed', label: 'MadsMainCruiseAllowed', description: 'Unknown setting from device', category: 'steering' },
    { key: 'Mads', label: 'Mads', description: 'Unknown setting from device', category: 'steering' },
    { key: 'MadsUnifiedEngagementMode', label: 'MadsUnifiedEngagementMode', description: 'Unknown setting from device', category: 'steering' },

    // Cruise
    { key: 'ExperimentalMode', label: 'Experimental Mode', description: 'Enable experimental features', category: 'cruise' },
    { key: 'SmartCruiseControlVision', label: 'SmartCruiseControlVision', description: 'Unknown setting from device', category: 'cruise' },
    { key: 'SpeedLimitPolicy', label: 'SpeedLimitPolicy', description: 'Unknown setting from device', category: 'cruise' },
    { key: 'SpeedLimitOffsetType', label: 'SpeedLimitOffsetType', description: 'Unknown setting from device', category: 'cruise' },
    { key: 'SmartCruiseControlMap', label: 'SmartCruiseControlMap', description: 'Unknown setting from device', category: 'cruise' },
    { key: 'MapAdvisorySpeedLimit', label: 'MapAdvisorySpeedLimit', description: 'Unknown setting from device', category: 'cruise' },

    // Visuals
    { key: 'Brightness', label: 'Brightness', description: 'Screen brightness level', category: 'visuals' },
    { key: 'BrightnessOff', label: 'Brightness (Off)', description: 'Screen brightness when off', category: 'visuals' },
    { key: 'RoadNameToggle', label: 'RoadNameToggle', description: 'Unknown setting from device', category: 'visuals' },
    { key: 'RoadName', label: 'RoadName', description: 'Unknown setting from device', category: 'visuals' },
    { key: 'BlindSpot', label: 'BlindSpot', description: 'Unknown setting from device', category: 'visuals' },
    { key: 'StandstillTimer', label: 'StandstillTimer', description: 'Unknown setting from device', category: 'visuals' },
    { key: 'RainbowMode', label: 'RainbowMode', description: 'Unknown setting from device', category: 'visuals' },
    { key: 'OnroadScreenOffTimer', label: 'OnroadScreenOffTimer', description: 'Unknown setting from device', category: 'visuals' },
    { key: 'OnroadScreenOffControl', label: 'OnroadScreenOffControl', description: 'Unknown setting from device', category: 'visuals' },
    { key: 'OnroadScreenOffBrightness', label: 'OnroadScreenOffBrightness', description: 'Unknown setting from device', category: 'visuals' },

    // Developer
    { key: 'ApiCache_DriveStats', label: 'API Cache: Drive Stats', description: 'Drive stats cache', category: 'developer', advanced: true, readonly: true },
    { key: 'ApiCache_Device', label: 'API Cache: Device', description: 'Device info cache', category: 'developer', advanced: true, readonly: true },
    { key: 'ApiCache_NavDestinations', label: 'API Cache: Nav Destinations', description: 'Navigation cache', category: 'developer', advanced: true, readonly: true },
    { key: 'AthenadPid', label: 'Athena PID', description: 'Athena process ID', category: 'developer', readonly: true, hidden: true },
    { key: 'BootCount', label: 'Boot Count', description: 'Number of boots', category: 'developer', advanced: true, readonly: true },
    { key: 'CalibrationParams', label: 'Calibration Params', description: 'Camera calibration data', category: 'developer', readonly: true, hidden: true },
    { key: 'CarBatteryCapacity', label: 'Car Battery Capacity', description: 'Battery size in kWh', category: 'developer', advanced: true, readonly: true },
    { key: 'CarParams', label: 'Car Params', description: 'Vehicle parameters', category: 'developer', readonly: true, hidden: true },
    { key: 'CarParamsCache', label: 'Car Params Cache', description: 'Cached vehicle params', category: 'developer', readonly: true, hidden: true },
    { key: 'CarVin', label: 'Car VIN', description: 'Vehicle identification', category: 'developer', advanced: true, readonly: true },
    { key: 'CompletedTrainingVersion', label: 'Training Version', description: 'Last completed training', category: 'developer', advanced: true, readonly: true },
    { key: 'ControlsReady', label: 'Controls Ready', description: 'System ready status', category: 'developer', readonly: true, hidden: true },
    { key: 'CurrentRoute', label: 'Current Route', description: 'Active drive route', category: 'developer', readonly: true, hidden: true },
    { key: 'IMEI', label: 'IMEI', description: 'Cellular modem ID', category: 'developer', advanced: true, readonly: true },
    { key: 'InstallDate', label: 'Install Date', description: 'Installation timestamp', category: 'developer', advanced: true, readonly: true },
    { key: 'IsEngaged', label: 'Is Engaged', description: 'Currently engaged', category: 'developer', readonly: true, hidden: true },
    { key: 'IsFcwEnabled', label: 'FCW Enabled', description: 'Forward collision warning', category: 'developer', advanced: true, readonly: true },
    { key: 'IsOffroad', label: 'Is Offroad', description: 'Not currently driving', category: 'developer', readonly: true, hidden: true },
    { key: 'IsOnroad', label: 'Is Onroad', description: 'Currently driving', category: 'developer', readonly: true, hidden: true },
    { key: 'IsReleaseBranch', label: 'Is Release Branch', description: 'On release software', category: 'developer', readonly: true, hidden: true },
    { key: 'IsTestedBranch', label: 'Is Tested Branch', description: 'On tested software', category: 'developer', readonly: true, hidden: true },
    { key: 'IsUpdateAvailable', label: 'Update Available', description: 'Update pending', category: 'developer', readonly: true, hidden: true },
    { key: 'LastAthenaPingTime', label: 'Last Athena Ping', description: 'Last server contact', category: 'developer', readonly: true, hidden: true },
    { key: 'LastGPSPosition', label: 'Last GPS Position', description: 'GPS coordinates', category: 'developer', readonly: true, hidden: true },
    { key: 'LastOffroadStatusPacket', label: 'Last Offroad Packet', description: 'Last status update', category: 'developer', readonly: true, hidden: true },
    { key: 'LastUpdateException', label: 'Last Update Exception', description: 'Update error info', category: 'developer', advanced: true, readonly: true },
    { key: 'LastUpdateTime', label: 'Last Update Time', description: 'Last update timestamp', category: 'developer', advanced: true, readonly: true },
    { key: 'LiveParameters', label: 'Live Parameters', description: 'Runtime parameters', category: 'developer', readonly: true, hidden: true },
    { key: 'NavDestination', label: 'Nav Destination', description: 'Navigation target', category: 'developer', readonly: true, hidden: true },
    { key: 'NavSettingLeftSide', label: 'Nav Left Side', description: 'Left-side navigation', category: 'developer', advanced: true },
    { key: 'NavSettingTime24h', label: 'Nav 24h Time', description: '24-hour time format', category: 'developer', advanced: true },
    { key: 'NavdRender', label: 'Nav Render', description: 'Navigation rendering', category: 'developer', advanced: true },
    { key: 'NetworkMetered', label: 'Network Metered', description: 'Metered connection', category: 'developer', advanced: true },
    { key: 'NetworkType', label: 'Network Type', description: 'Connection type', category: 'developer', advanced: true, readonly: true },
    { key: 'Offroad_BadNvme', label: 'Offroad: Bad NVMe', description: 'Storage error', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_CarUnrecognized', label: 'Offroad: Car Unrecognized', description: 'Unknown vehicle', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_ConnectivityNeeded', label: 'Offroad: Connectivity Needed', description: 'Internet required', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_InvalidTime', label: 'Offroad: Invalid Time', description: 'Time sync error', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_IsTakingSnapshot', label: 'Offroad: Taking Snapshot', description: 'Snapshot in progress', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_NeosUpdate', label: 'Offroad: NEOS Update', description: 'OS update required', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_NoFirmware', label: 'Offroad: No Firmware', description: 'Firmware missing', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_StorageMissing', label: 'Offroad: Storage Missing', description: 'Storage not found', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_TemperatureTooHigh', label: 'Offroad: Temperature High', description: 'Overheating', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_UnofficialHardware', label: 'Offroad: Unofficial Hardware', description: 'Unsupported device', category: 'developer', readonly: true, hidden: true },
    { key: 'Offroad_UpdateFailed', label: 'Offroad: Update Failed', description: 'Update error', category: 'developer', readonly: true, hidden: true },
    { key: 'Passive', label: 'Passive', description: 'Passive mode', category: 'developer', readonly: true, hidden: true },
    { key: 'PrimeRedirected', label: 'Prime Redirected', description: 'Prime redirect status', category: 'developer', readonly: true, hidden: true },
    { key: 'PrimeType', label: 'Prime Type', description: 'Prime subscription type', category: 'developer', readonly: true, hidden: true },
    { key: 'SnoozeUpdate', label: 'Snooze Update', description: 'Update snooze timer', category: 'developer', readonly: true, hidden: true },
    { key: 'SshEnabled', label: 'SSH Enabled', description: 'SSH access enabled', category: 'developer', advanced: true },
    { key: 'TermsVersion', label: 'Terms Version', description: 'Accepted terms version', category: 'developer', readonly: true, hidden: true },
    { key: 'TrainingVersion', label: 'Training Version', description: 'Training software version', category: 'developer', readonly: true, hidden: true },
    { key: 'UpdateAvailable', label: 'Update Available', description: 'Update ready', category: 'developer', advanced: true, readonly: true },
    { key: 'UpdateFailedCount', label: 'Update Failed Count', description: 'Failed update attempts', category: 'developer', advanced: true, readonly: true },
    { key: 'UpdaterAvailableBranches', label: 'Available Branches', description: 'Update branches', category: 'developer', advanced: true, readonly: true },
    { key: 'UpdaterCurrentDescription', label: 'Current Description', description: 'Current branch info', category: 'developer', readonly: true, hidden: true },
    { key: 'UpdaterCurrentReleaseNotes', label: 'Current Release Notes', description: 'Release notes', category: 'developer', readonly: true, hidden: true },
    { key: 'UpdaterFetchAvailable', label: 'Updater Fetch Available', description: 'Update check ready', category: 'developer', readonly: true, hidden: true },
    { key: 'UpdaterNewDescription', label: 'New Description', description: 'New version info', category: 'developer', readonly: true, hidden: true },
    { key: 'UpdaterNewReleaseNotes', label: 'New Release Notes', description: 'New release notes', category: 'developer', readonly: true, hidden: true },
    { key: 'UpdaterState', label: 'Updater State', description: 'Update system state', category: 'developer', readonly: true, hidden: true },
    { key: 'UpdaterTargetBranch', label: 'Target Branch', description: 'Update target branch', category: 'developer', advanced: true, readonly: true },
    { key: 'LagdToggleDelay', label: 'LagdToggleDelay', description: 'Unknown setting from device', category: 'developer', advanced: true },
    { key: 'LagdToggle', label: 'LagdToggle', description: 'Unknown setting from device', category: 'developer', advanced: true },
    { key: 'SubaruStopAndGoManualParkingBrake', label: 'SubaruStopAndGoManualParkingBrake', description: 'Unknown setting from device', category: 'developer', advanced: true },
    { key: 'HyundaiLongitudinalTuning', label: 'HyundaiLongitudinalTuning', description: 'Unknown setting from device', category: 'developer', advanced: true },
    { key: 'ModelManager_Favs', label: 'ModelManager_Favs', description: 'Unknown setting from device', category: 'developer', advanced: true, readonly: true },
    { key: 'ModelManager_ActiveBundle', label: 'ModelManager_ActiveBundle', description: 'Unknown setting from device', category: 'developer', advanced: true, readonly: true },
    { key: 'ShowAdvancedControls', label: 'ShowAdvancedControls', description: 'Unknown setting from device', category: 'developer', advanced: true },
    { key: 'QuickBootToggle', label: 'QuickBootToggle', description: 'Unknown setting from device', category: 'developer', advanced: true },

    // Other
    { key: 'HkgTuningOverridingCycles', label: 'HkgTuningOverridingCycles', description: 'Unknown setting from device', category: 'other', advanced: true },
    { key: 'HkgTuningAngleActiveTorqueReductionGain', label: 'HkgTuningAngleActiveTorqueReductionGain', description: 'Unknown setting from device', category: 'other', advanced: true },
    { key: 'HkgTuningAngleMinTorqueReductionGain', label: 'HkgTuningAngleMinTorqueReductionGain', description: 'Unknown setting from device', category: 'other', advanced: true },
    { key: 'EnableHkgTuningAngleSmoothingFactor', label: 'EnableHkgTuningAngleSmoothingFactor', description: 'Unknown setting from device', category: 'other', advanced: true },
    { key: 'LiveTorqueParamsRelaxedToggle', label: 'LiveTorqueParamsRelaxedToggle', description: 'Unknown setting from device', category: 'other', advanced: true },
    { key: 'OsmStateName', label: 'OsmStateName', description: 'Unknown setting from device', category: 'other' },
    { key: 'OsmLocationTitle', label: 'OsmLocationTitle', description: 'Unknown setting from device', category: 'other' },
    { key: 'OsmLocationName', label: 'OsmLocationName', description: 'Unknown setting from device', category: 'other' },
    { key: 'OSMDownloadProgress', label: 'OSMDownloadProgress', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'OSMDownloadLocations', label: 'OSMDownloadLocations', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'OsmDownloadedDate', label: 'OsmDownloadedDate', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'Offroad_OSMUpdateRequired', label: 'Offroad_OSMUpdateRequired', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'MapdVersion', label: 'MapdVersion', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'LaneTurnValue', label: 'LaneTurnValue', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'BackupManager_CreateBackup', label: 'BackupManager_CreateBackup', description: 'Unknown setting from device', category: 'other' },
    { key: 'SunnylinkTempFault', label: 'SunnylinkTempFault', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'SunnylinkCache_Users', label: 'SunnylinkCache_Users', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'SunnylinkCache_Roles', label: 'SunnylinkCache_Roles', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'ModelManager_ModelsCache', label: 'ModelManager_ModelsCache', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'SunnylinkDongleId', label: 'SunnylinkDongleId', description: 'Unknown setting from device', category: 'other', readonly: true },
    { key: 'Offroad_TiciSupport', label: 'Offroad_TiciSupport', description: 'Unknown setting from device', category: 'other', advanced: true },
    { key: 'IsReleaseSpBranch', label: 'IsReleaseSpBranch', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'TorqueParamsOverrideLatAccelFactor', label: 'TorqueParamsOverrideLatAccelFactor', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'SunnylinkEnabled', label: 'SunnylinkEnabled', description: 'Unknown setting from device', category: 'other', hidden: true },
    { key: 'InteractivityTimeout', label: 'InteractivityTimeout', description: 'Unknown setting from device', category: 'other' },
    { key: 'GreenLightAlert', label: 'GreenLightAlert', description: 'Unknown setting from device', category: 'other' },
    { key: 'EnableCopyparty', label: 'EnableCopyparty', description: 'Unknown setting from device', category: 'other' },
    { key: 'DevUIInfo', label: 'DevUIInfo', description: 'Unknown setting from device', category: 'other' },
    { key: 'DeviceBootMode', label: 'DeviceBootMode', description: 'Unknown setting from device', category: 'other' },
    { key: 'CustomAccLongPressIncrement', label: 'CustomAccLongPressIncrement', description: 'Unknown setting from device', category: 'other' },
    { key: 'CustomAccIncrementsEnabled', label: 'CustomAccIncrementsEnabled', description: 'Unknown setting from device', category: 'other' },
    { key: 'ChevronInfo', label: 'ChevronInfo', description: 'Unknown setting from device', category: 'other' },
    { key: 'CarParamsSPCache', label: 'CarParamsSPCache', description: 'Unknown setting from device', category: 'other' },
    { key: 'CarParamsSP', label: 'CarParamsSP', description: 'Unknown setting from device', category: 'other' },
    { key: 'CustomTorqueParams', label: 'CustomTorqueParams', description: 'Unknown setting from device', category: 'other' },
    { key: 'BlinkerMinLateralControlSpeed', label: 'BlinkerMinLateralControlSpeed', description: 'Unknown setting from device', category: 'other' },
    { key: 'MapSpeedLimit', label: 'MapSpeedLimit', description: 'Unknown setting from device', category: 'other' },
    { key: 'ModelRunnerTypeCache', label: 'ModelRunnerTypeCache', description: 'Unknown setting from device', category: 'other' },
    { key: 'OnroadCycleRequested', label: 'OnroadCycleRequested', description: 'Unknown setting from device', category: 'other' },
    { key: 'OSMDownloadBounds', label: 'OSMDownloadBounds', description: 'Unknown setting from device', category: 'other' },
    { key: 'UpdaterLastFetchTime', label: 'UpdaterLastFetchTime', description: 'Unknown setting from device', category: 'other' },
    { key: 'GitRemote', label: 'GitRemote', description: 'Unknown setting from device', category: 'other' },
    { key: 'GsmRoaming', label: 'GsmRoaming', description: 'Unknown setting from device', category: 'other' },
    { key: 'ShowTurnSignals', label: 'ShowTurnSignals', description: 'Unknown setting from device', category: 'other' },
    { key: 'GithubRunnerSufficientVoltage', label: 'GithubRunnerSufficientVoltage', description: 'Unknown setting from device', category: 'other' },
    { key: 'CameraDebugExpGain', label: 'CameraDebugExpGain', description: 'Unknown setting from device', category: 'other' },
    { key: 'ApiCache_FirehoseStats', label: 'ApiCache_FirehoseStats', description: 'Unknown setting from device', category: 'other' },
    { key: 'DriverTooDistracted', label: 'DriverTooDistracted', description: 'Unknown setting from device', category: 'other' },
    { key: 'OsmDbUpdatesCheck', label: 'OsmDbUpdatesCheck', description: 'Unknown setting from device', category: 'other' },
    { key: 'JoystickDebugMode', label: 'JoystickDebugMode', description: 'Unknown setting from device', category: 'other' },
    { key: 'ModelManager_LastSyncTime', label: 'ModelManager_LastSyncTime', description: 'Unknown setting from device', category: 'other' },
    { key: 'AthenadRecentlyViewedRoutes', label: 'AthenadRecentlyViewedRoutes', description: 'Unknown setting from device', category: 'other' },
    { key: 'TorqueParamsOverrideEnabled', label: 'TorqueParamsOverrideEnabled', description: 'Unknown setting from device', category: 'other' },
    { key: 'IsRhdDetected', label: 'IsRhdDetected', description: 'Unknown setting from device', category: 'other' },
    { key: 'GitDiff', label: 'GitDiff', description: 'Unknown setting from device', category: 'other' },
    { key: 'IsDevelopmentBranch', label: 'IsDevelopmentBranch', description: 'Unknown setting from device', category: 'other' },
    { key: 'IsDriverViewEnabled', label: 'IsDriverViewEnabled', description: 'Unknown setting from device', category: 'other' },
    { key: 'GitBranch', label: 'GitBranch', description: 'Unknown setting from device', category: 'other' },
    { key: 'BlinkerPauseLateralControl', label: 'BlinkerPauseLateralControl', description: 'Unknown setting from device', category: 'other' },
    { key: 'AthenadUploadQueue', label: 'AthenadUploadQueue', description: 'Unknown setting from device', category: 'other' },
    { key: 'ForcePowerDown', label: 'ForcePowerDown', description: 'Unknown setting from device', category: 'other' },
    { key: 'UptimeOffroad', label: 'UptimeOffroad', description: 'Unknown setting from device', category: 'other' },
    { key: 'AssistNowToken', label: 'AssistNowToken', description: 'Unknown setting from device', category: 'other' },
    { key: 'OsmLocationUrl', label: 'OsmLocationUrl', description: 'Unknown setting from device', category: 'other' },
    { key: 'GsmApn', label: 'GsmApn', description: 'Unknown setting from device', category: 'other' },
    { key: 'HideVEgoUI', label: 'HideVEgoUI', description: 'Unknown setting from device', category: 'other' },
    { key: 'CarParamsPrevRoute', label: 'CarParamsPrevRoute', description: 'Unknown setting from device', category: 'other' },
    { key: 'RecordFrontLock', label: 'RecordFrontLock', description: 'Unknown setting from device', category: 'other' },
    { key: 'AlwaysOnDM', label: 'AlwaysOnDM', description: 'Unknown setting from device', category: 'other' },
    { key: 'AutoLaneChangeBsmDelay', label: 'AutoLaneChangeBsmDelay', description: 'Unknown setting from device', category: 'other' },
    { key: 'TeslaCoopSteering', label: 'TeslaCoopSteering', description: 'Unknown setting from device', category: 'other' },
    { key: 'HasAcceptedTerms', label: 'HasAcceptedTerms', description: 'Unknown setting from device', category: 'other' },
    { key: 'CarPlatformBundle', label: 'CarPlatformBundle', description: 'Unknown setting from device', category: 'other' },
    { key: 'AdbEnabled', label: 'AdbEnabled', description: 'Unknown setting from device', category: 'other' },
    { key: 'ObdMultiplexingChanged', label: 'ObdMultiplexingChanged', description: 'Unknown setting from device', category: 'other' },
    { key: 'EnableSunnylinkUploader', label: 'EnableSunnylinkUploader', description: 'Unknown setting from device', category: 'other' },
    { key: 'LiveTorqueParameters', label: 'LiveTorqueParameters', description: 'Unknown setting from device', category: 'other' },
    { key: 'IntelligentCruiseButtonManagement', label: 'IntelligentCruiseButtonManagement', description: 'Unknown setting from device', category: 'other' },
    { key: 'CameraDebugExpTime', label: 'CameraDebugExpTime', description: 'Unknown setting from device', category: 'other' },
    { key: 'AccessToken', label: 'AccessToken', description: 'Unknown setting from device', category: 'other' },
    { key: 'HardwareSerial', label: 'HardwareSerial', description: 'Unknown setting from device', category: 'other' },
    { key: 'FirmwareQueryDone', label: 'FirmwareQueryDone', description: 'Unknown setting from device', category: 'other' },
    { key: 'DoReboot', label: 'DoReboot', description: 'Unknown setting from device', category: 'other' },
    { key: 'SunnylinkdPid', label: 'SunnylinkdPid', description: 'Unknown setting from device', category: 'other' },
    { key: 'ModelManager_DownloadIndex', label: 'ModelManager_DownloadIndex', description: 'Unknown setting from device', category: 'other' },
    { key: 'DoUninstall', label: 'DoUninstall', description: 'Unknown setting from device', category: 'other' },
    { key: 'ModelManager_ClearCache', label: 'ModelManager_ClearCache', description: 'Unknown setting from device', category: 'other' },
    { key: 'RouteCount', label: 'RouteCount', description: 'Unknown setting from device', category: 'other' },
    { key: 'OsmLocal', label: 'OsmLocal', description: 'Unknown setting from device', category: 'other' },
    { key: 'CurrentBootlog', label: 'CurrentBootlog', description: 'Unknown setting from device', category: 'other' },
    { key: 'GitCommitDate', label: 'GitCommitDate', description: 'Unknown setting from device', category: 'other' },
    { key: 'AlphaLongitudinalEnabled', label: 'AlphaLongitudinalEnabled', description: 'Unknown setting from device', category: 'other' },
    { key: 'UptimeOnroad', label: 'UptimeOnroad', description: 'Unknown setting from device', category: 'other' },
    { key: 'SubaruStopAndGo', label: 'SubaruStopAndGo', description: 'Unknown setting from device', category: 'other' },
    { key: 'Offroad_ExcessiveActuation', label: 'Offroad_ExcessiveActuation', description: 'Unknown setting from device', category: 'other' },
    { key: 'MapTargetVelocities', label: 'MapTargetVelocities', description: 'Unknown setting from device', category: 'other' },
    { key: 'LastManagerExitReason', label: 'LastManagerExitReason', description: 'Unknown setting from device', category: 'other' },
    { key: 'CarParamsSPPersistent', label: 'CarParamsSPPersistent', description: 'Unknown setting from device', category: 'other' },
    { key: 'SecOCKey', label: 'SecOCKey', description: 'Unknown setting from device', category: 'other' },
    { key: 'LastPowerDropDetected', label: 'LastPowerDropDetected', description: 'Unknown setting from device', category: 'other' },
    { key: 'OnroadUploads', label: 'OnroadUploads', description: 'Unknown setting from device', category: 'other' },
    { key: 'DoShutdown', label: 'DoShutdown', description: 'Unknown setting from device', category: 'other' },
    { key: 'LiveParametersV2', label: 'LiveParametersV2', description: 'Unknown setting from device', category: 'other' },
    { key: 'ShowDebugInfo', label: 'ShowDebugInfo', description: 'Unknown setting from device', category: 'other' },
    { key: 'LastUpdateRouteCount', label: 'LastUpdateRouteCount', description: 'Unknown setting from device', category: 'other' },
    { key: 'OsmWayTest', label: 'OsmWayTest', description: 'Unknown setting from device', category: 'other' },
    { key: 'LastUpdateUptimeOnroad', label: 'LastUpdateUptimeOnroad', description: 'Unknown setting from device', category: 'other' },
    { key: 'OffroadMode', label: 'OffroadMode', description: 'Unknown setting from device', category: 'other' },
    { key: 'RecordAudioFeedback', label: 'RecordAudioFeedback', description: 'Unknown setting from device', category: 'other' },
    { key: 'LagdValueCache', label: 'LagdValueCache', description: 'Unknown setting from device', category: 'other' },
    { key: 'EnableGithubRunner', label: 'EnableGithubRunner', description: 'Unknown setting from device', category: 'other' },
    { key: 'LiveDelay', label: 'LiveDelay', description: 'Unknown setting from device', category: 'other' },
    { key: 'LocationFilterInitialState', label: 'LocationFilterInitialState', description: 'Unknown setting from device', category: 'other' },
    { key: 'SpeedLimitMode', label: 'SpeedLimitMode', description: 'Unknown setting from device', category: 'other' },
    { key: 'LongitudinalManeuverMode', label: 'LongitudinalManeuverMode', description: 'Unknown setting from device', category: 'other' },
    { key: 'NextMapSpeedLimit', label: 'NextMapSpeedLimit', description: 'Unknown setting from device', category: 'other' },
    { key: 'PandaHeartbeatLost', label: 'PandaHeartbeatLost', description: 'Unknown setting from device', category: 'other' },
    { key: 'LeadDepartAlert', label: 'LeadDepartAlert', description: 'Unknown setting from device', category: 'other' },
    { key: 'CustomAccShortPressIncrement', label: 'CustomAccShortPressIncrement', description: 'Unknown setting from device', category: 'other' },
    { key: 'OsmStateTitle', label: 'OsmStateTitle', description: 'Unknown setting from device', category: 'other' },
    { key: 'Offroad_ConnectivityNeededPrompt', label: 'Offroad_ConnectivityNeededPrompt', description: 'Unknown setting from device', category: 'other' },
    { key: 'LaneTurnDesire', label: 'LaneTurnDesire', description: 'Unknown setting from device', category: 'other' },
    { key: 'BackupManager_RestoreVersion', label: 'BackupManager_RestoreVersion', description: 'Unknown setting from device', category: 'other' },
    { key: 'ExperimentalModeConfirmed', label: 'ExperimentalModeConfirmed', description: 'Unknown setting from device', category: 'other' },
    { key: 'Offroad_Recalibration', label: 'Offroad_Recalibration', description: 'Unknown setting from device', category: 'other' },
    { key: 'Offroad_UnregisteredHardware', label: 'Offroad_UnregisteredHardware', description: 'Unknown setting from device', category: 'other' },
    { key: 'LastGPSPositionLLK', label: 'LastGPSPositionLLK', description: 'Unknown setting from device', category: 'other' },
    { key: 'DisengageOnAccelerator', label: 'DisengageOnAccelerator', description: 'Unknown setting from device', category: 'other' },
    { key: 'ObdMultiplexingEnabled', label: 'ObdMultiplexingEnabled', description: 'Unknown setting from device', category: 'other' },
    { key: 'Offroad_DriverMonitoringUncertain', label: 'Offroad_DriverMonitoringUncertain', description: 'Unknown setting from device', category: 'other' },
    { key: 'SpeedLimitValueOffset', label: 'SpeedLimitValueOffset', description: 'Unknown setting from device', category: 'other' },
    { key: 'DynamicExperimentalControl', label: 'DynamicExperimentalControl', description: 'Unknown setting from device', category: 'other' },
    { key: 'PandaSomResetTriggered', label: 'PandaSomResetTriggered', description: 'Unknown setting from device', category: 'other' },
    { key: 'PandaSignatures', label: 'PandaSignatures', description: 'Unknown setting from device', category: 'other' },
    { key: 'UbloxAvailable', label: 'UbloxAvailable', description: 'Unknown setting from device', category: 'other' },
    { key: 'HkgTuningAngleMaxTorqueReductionGain', label: 'HkgTuningAngleMaxTorqueReductionGain', description: 'Unknown setting from device', category: 'other' },
    { key: 'CarParamsPersistent', label: 'CarParamsPersistent', description: 'Unknown setting from device', category: 'other' },
    { key: 'RecordAudio', label: 'RecordAudio', description: 'Unknown setting from device', category: 'other' },
    { key: 'TrueVEgoUI', label: 'TrueVEgoUI', description: 'Unknown setting from device', category: 'other' },
    { key: 'AutoLaneChangeTimer', label: 'AutoLaneChangeTimer', description: 'Unknown setting from device', category: 'other' },
    { key: 'LastSunnylinkPingTime', label: 'LastSunnylinkPingTime', description: 'Unknown setting from device', category: 'other' },
    { key: 'IsTakingSnapshot', label: 'IsTakingSnapshot', description: 'Unknown setting from device', category: 'other' },
    { key: 'TorqueParamsOverrideFriction', label: 'TorqueParamsOverrideFriction', description: 'Unknown setting from device', category: 'other' },
];